// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/arkdbp/jobservice/lib"
	"github.com/arkdbp/jobservice/server"
)

// Injectors from wire.go:

func WireApp(c *server.Config) *server.App {
	logger := server.NewLogger()
	memRepo := lib.NewMemRepo()
	cmdProcessor := lib.NewCmdProcessor(logger, memRepo)
	serviceServer := server.NewServiceServer(cmdProcessor, logger)
	app := server.NewServer(c, serviceServer, logger)
	return app
}
